version: '3.8'

services:
# Bizim API servisi
  backend:
    build: ./backend
    container_name: backend_service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db/events_db
    depends_on:
      - db

# PostgreSQL veritabanı servisi
  db:
    image: postgres:15
    container_name: db_service
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=events_db
    ports:
      - "5432:5432"

  # etl_worker servisi
  etl_worker:
    build: ./etl_worker
    container_name: etl_service
    restart: always
    environment:
      - DATABASE_URL=postgresql://user:password@db/events_db
    depends_on:
      - db
    # Modelleri ortak kullanabilmek için backend klasörünü buraya da bağlıyoruz
    volumes:
      - ./backend:/app/models_folder

# 4. Frontend (Next.js) - YENİ EKLENDİ
  frontend:
    build: ./frontend
    container_name: frontend_service
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend

volumes:
  postgres_data: