version: '3.8'

services:
# Bizim API servisi
  backend:
    build: ./backend
    container_name: backend_service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db/events_db
    depends_on:
      - db

# PostgreSQL veritabanÄ± servisi
  db:
    image: postgres:15
    container_name: db_service
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=events_db
    ports:
      - "5432:5432"